feat(release) Add craft descriptor and release workflow
getsentry/wal2json pull request #11
Opened 2021-04-16 06:41 UTC by fpacifici

This is supposed to set up releasing for this project according to https://github.com/getsentry/craft#integrating-your-project-with-craft.

Specifically it adds the release GHA workflow and the craft descriptor file that publish the binary generated by the `build_library` workflow in the sentry registry.

2021-04-16 16:24 UTC, evanh reviewed
I think you also need a `bump_version.sh` script. The release action calls that script to update the version number in your codebase before committing. See https://github.com/getsentry/snuba-sdk/blob/main/scripts/bump-version.sh

2021-04-19 15:35 UTC, fpacifici commented
I don't think the version is stored anywhere in the code base. Is it actually needed ?

2021-04-19 20:30 UTC, BYK requested changes

2021-04-20 06:57 UTC, fpacifici commented on .craft.yml
> +  - name: github
fixed

2021-04-20 06:58 UTC, fpacifici commented on .craft.yml
> +      canonical: "app:relay"
Well, I thought publishing to the registry was required. It seemed so from the docs. But you are right, it is enough for the file to be downloadable. 

Should I just remove the registry target entirely ?

2021-04-20 08:01 UTC, BYK commented on .craft.yml
> +      canonical: "app:relay"
>I removed the entire target. Is this the right way?

Yup, let's go without the registry for now.

2021-04-20 08:02 UTC, BYK approved these changes

2021-04-20 21:43 UTC, merged